### ISSUE TITLE
Fix crappy CSS and convert to tailwind

### ISSUE THREAD

**Issue by robiningelbrecht** [robiningelbrecht/strava-activities-template#103]
```css
.text-strava-orange{
    color: #F26722;
}

.w-18{
    width: 4.5rem;
}

.z-60{
    z-index: 60;
}

.z-70{
    z-index: 70;
}

[data-tabs-toggle] li a[aria-selected="true"]{
    color: #FC4A02;
    border-color: #FC4A02;
}
```
